/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.miwashi.stijdbc;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.*;

public class App {
    private static final Logger LOGGER = LoggerFactory.getLogger( App.class );

    public static void main(String[] args) {
        System.out.println("Running");
        System.out.println("Running");
        System.out.println("Running");
        Connection con = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Chinook", "sti", "sti");
            ResultSet rs = con.createStatement().executeQuery("select * from Artist");
            while(rs.next()) {
                //System.out.print(rs.getString(1));
                Integer id = rs.getInt("ArtistId");
                String name = rs.getString("Name");
                Artist artist = new Artist(id, name);
                System.out.println(artist);
            }
        } catch (ClassNotFoundException e) {
            LOGGER.warn("Driver for mysql is not in classpath!", e);
        } catch (SQLException e) {
            LOGGER.warn("Exception caught when connection to database!", e);
        } finally {
            if(con!=null) {
                try {
                    con.close();
                } catch (SQLException ignore) {
                    LOGGER.warn("Unable to close connection!", ignore);
                }
            }
        }
    }
}
