/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.miwashi.stijdbc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stidb", "sti", "sti");
        } catch (ClassNotFoundException e) {
            System.err.println("Driver for mysql is not in classpath!");
            System.err.println(e);
        } catch (SQLException e) {
            System.err.println("Exception caught when connection to database!");
            System.err.println(e);
        }
    }
}
